/**
* Augmented City API
* ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
*
* The version of the OpenAPI document: 2.0.0
* Contact: support@vergendo.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ac.api.models

import com.ac.api.models.AugmentedCityDescription

import com.squareup.moshi.Json

/**
 * Information about the augmented city. Includes name, country and geometry of the city.
 * @param cityId Numeric identifier of the city
 * @param city Name of the city
 * @param country Name of the country where the city is located
 * @param description 
 */

data class AugmentedCity (
    /* Numeric identifier of the city */
    @Json(name = "city_id")
    val cityId: kotlin.Int,
    /* Name of the city */
    @Json(name = "city")
    val city: kotlin.String,
    /* Name of the country where the city is located */
    @Json(name = "country")
    val country: kotlin.String,
    @Json(name = "description")
    val description: AugmentedCityDescription
)

