/**
* Augmented City API
* ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
*
* The version of the OpenAPI document: 2.0.0
* Contact: support@vergendo.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ac.api.models


import com.squareup.moshi.Json

/**
 * Intrinsics are based on physical characteristics of the device camera and a pinhole camera model.
 * @param fx Focal length
 * @param fy Focal length
 * @param cx Principal point
 * @param cy Principal point
 */

data class CameraIntrinsics (
    /* Focal length */
    @Json(name = "fx")
    val fx: kotlin.Float,
    /* Focal length */
    @Json(name = "fy")
    val fy: kotlin.Float,
    /* Principal point */
    @Json(name = "cx")
    val cx: kotlin.Float,
    /* Principal point */
    @Json(name = "cy")
    val cy: kotlin.Float
)

