/**
* Augmented City API
* ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
*
* The version of the OpenAPI document: 2.0.0
* Contact: support@vergendo.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ac.api.models


import com.squareup.moshi.Json

/**
 * Single geo position geometry type
 * @param type 
 * @param coordinates Geo position in 3D space. A position is an array of numbers. There MUST be two or three elements. The first two elements are longitude and latitude, or easting and northing, precisely in that order and using decimal numbers. Altitude or elevation MAY be included as an optional third element.
 */

data class GeoPoint (
    @Json(name = "type")
    val type: GeoPoint.Type,
    /* Geo position in 3D space. A position is an array of numbers. There MUST be two or three elements. The first two elements are longitude and latitude, or easting and northing, precisely in that order and using decimal numbers. Altitude or elevation MAY be included as an optional third element. */
    @Json(name = "coordinates")
    val coordinates: kotlin.collections.List<java.math.BigDecimal>
) {

    /**
    * 
    * Values: point
    */
    
    enum class Type(val value: kotlin.String){
        @Json(name = "Point") point("Point");
    }
}

